### ISSUE TITLE
TypeError: Cannot read property 'buildMeta' of undefined

### ISSUE THREAD

**Issue by rngadam** [purtuga/esm-webpack-plugin#4]
config:

```
const path = require('path');
const webpack = require("webpack");
const EsmWebpackPlugin = require("@purtuga/esm-webpack-plugin");

module.exports = {
  entry:  path.resolve(__dirname, 'src/index.js'),
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'ohmq.bundle.js',
    library: 'ohmq',
    libraryTarget: "var"
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
    }
  },
  plugins: [
    new EsmWebpackPlugin()
  ]
};
```

error:

```
/src/node_modules/@purtuga/esm-webpack-plugin/esm-webpack-plugin.js:51
            if (chunk.entryModule.buildMeta.providedExports) {
                                  ^

TypeError: Cannot read property 'buildMeta' of undefined
    at chunks.forEach.chunk (/src/node_modules/@purtuga/esm-webpack-plugin/esm-webpack-plugin.js:51:35)
    at Array.forEach (<anonymous>)
    at compilation.hooks.optimizeChunkAssets.tapAsync (/src/node_modules/@purtuga/esm-webpack-plugin/esm-webpack-plugin.js:50:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (/src/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/src/node_modules/webpack/lib/Compilation.js:1315:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/src/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/src/node_modules/webpack/lib/Compilation.js:1311:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/src/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/src/node_modules/webpack/lib/Compilation.js:1248:27)
    at compilation.finish.err (/src/node_modules/webpack/lib/Compiler.js:625:18)
    at hooks.finishModules.callAsync.err (/src/node_modules/webpack/lib/Compilation.js:1171:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/src/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/src/node_modules/webpack/lib/Compilation.js:1163:28)
    at hooks.make.callAsync.err (/src/node_modules/webpack/lib/Compiler.js:622:17)
    at _err0 (eval at create (/src/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (/src/node_modules/webpack/lib/Compilation.js:1095:12)
    at processModuleDependencies.err (/src/node_modules/webpack/lib/Compilation.js:1007:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by purtuga** [comment]
Thanks for reporting this. I think this is happening because of code splitting and the output of async chunks. Is that correct for your library?

Will look at this in more detail soon...

Paul

-- sent from mobile

**Comment by purtuga** [comment]
What version of webpack are you using?

**Comment by purtuga** [comment]
never mind. I was able to recreate it. Issue is due to auto code splitting. Working on a fix.

**Comment by rngadam** [comment]
nice turnaround on the fix! Thanks!

**Comment by 17736638254** [comment]
Hello, I also encountered this problem. How can I solve it?
`
"webpack": "^5.70.0",

 "webpack-cli": "^4.9.2",

 "webpack-dev-server": "^4.7.4",

 "webpack-merge": "^5.8.0"
`

**Comment by 17736638254** [comment]
Hello, I have encountered a similar problem. How can I solve it?

**Comment by 17736638254** [comment]
Hello, I have encountered a similar problem. How can I solve it?
<img width="336" alt="image" src="https://user-images.githubusercontent.com/59221382/161214534-034cd4e2-ba9f-4c53-aab8-f0bc7b081121.png">

<img width="986" alt="image" src="https://user-images.githubusercontent.com/59221382/161214421-0bca9d0e-e3d8-4305-822a-dec49a920c87.png">
